- "git://github.com/tpope/vim-repeat.git"
- "git://github.com/tpope/vim-rails.git"
- "git://github.com/tpope/vim-cucumber.git"
- "git://github.com/tpope/vim-surround.git"
- "git://github.com/tpope/vim-fugitive.git"
- "git://github.com/tpope/vim-markdown.git"
- "git://github.com/tpope/vim-unimpaired.git"
- "git://github.com/tpope/vim-vividchalk.git"
- "git://github.com/tpope/vim-ragtag.git"
- "git://github.com/tpope/vim-liquid.git"
- "git://github.com/tpope/vim-git.git"
- "git://github.com/tpope/vim-pastie.git"
- "git://github.com/tpope/vim-haml.git"
- "git://github.com/nono/github_vim_theme.git"
