#!/usr/bin/ruby

require 'pathname'

ROOT = File.dirname(Pathname.new(__FILE__).realpath)
SUBMODULES_DIR = 'bundle'

if ARGV.include? '--clone'
  require 'yaml'
  repos = YAML::load_file(File.join(ROOT, '.vimscripts.yml'))
  repos.each do |repo|
    script_name = File.basename(repo).gsub(/\.git$/, '')
    submodule_dir = File.join(SUBMODULES_DIR, script_name)
    if not File.exists? submodule_dir
      puts "Adding submodule '#{repo}' to '#{submodule_dir}'"
      system "git", "submodule", "--quiet", "add", repo, submodule_dir
    else
      puts "[WARNING] The path #{submodule_dir} already exists, skipping cloning of #{script_name}"
    end
  end
else
  Dir[File.join(SUBMODULES_DIR, "*")].each do |submodule|
    if File.exists? File.join(submodule, '.git')
      puts "Updating #{File.basename(submodule)}"
      system "git", "checkout", "--quiet", "master"
      system "git", "pull", "--quiet"
    end
  end
end
