#!/usr/bin/env ruby

require 'pathname'

ROOT = File.dirname(Pathname.new(__FILE__).realpath)
BUNDLES_DIR = 'bundle'

if !File.exists?(File.join(ROOT,BUNDLES_DIR)) or ARGV.include?('--install')
  require 'yaml'
  require 'fileutils'

  repos = YAML::load_file(File.join(ROOT, 'bundles.yml'))

  Dir.chdir(ROOT)

  repos.each do |repo|
    script_name = File.basename(repo).gsub(/\.git$/, '')
    bundle_dir = File.join(BUNDLES_DIR, script_name)
    if !File.exists?(bundle_dir) || ARGV.include?('-f')
      FileUtils.rm_f bundle_dir
      puts "Adding bundle '#{script_name}'"
      system "git", "clone", "--quiet", repo, bundle_dir
    else
      puts "[WARNING] The path #{bundle_dir} already exists, skipping cloning of #{script_name} (use -f to force overwriting)."
    end
  end
else
  Dir[File.join(BUNDLES_DIR, "*")].each do |bundle|
    if File.exists? File.join(bundle, '.git')
      puts "Updating #{File.basename(bundle)}"
      Dir.chdir(bundle) do
        system "git", "checkout", "--quiet", "master"
        system "git", "pull", "--quiet"
      end
    end
  end
end
